language: ruby
cache:
- bundler
install:
- bundle install
rvm:
- 2.1
- 2.2
- 2.3.0
- 2.4.1
notifications:
  email:
    recipients:
    - sensu-plugin@sensu-plugins.io
    on_success: change
    on_failure: always
script:
- bundle exec rake default
- gem build sensu-plugins-uptime-checks.gemspec
- gem install sensu-plugins-uptime-checks-*.gem
before_deploy:
- bash -c "[ ! -d bonsai/ ] && git clone https://github.com/sensu/sensu-go-bonsai-asset.git bonsai || echo 'bonsai/ exists, skipping git clone'"
deploy:
- provider: rubygems
  api_key:
    secure: Ea6nvAMqBhuWhlOkxgvY9M/ZI241wfa65pviBlQbt0dUC8j8SggsJ7hgdM4qE6c5pxhAOezuazAN/Qoh8zo7hpM5wqfzaq5+4WUuj48+y+8EGWI1x8u8DwKqnk2IU1uPST0uuG33yEFpHaaPU1NJyi/OxQ7pKA0jFjC+MyjojFc=
  gem: sensu-plugins-uptime-checks
  on:
    tags: true
    all_branches: true
    rvm: 2.1
    rvm: 2.2
    rvm: 2.3.0
    rvm: 2.4.1
    repo: sensu-plugins/sensu-plugins-uptime-checks
- provider: script
  script: bonsai/ruby-runtime/travis-build-ruby-plugin-assets.sh sensu-plugins-uptime-checks
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
    rvm: 2.4.1
env:
  global:
    secure: tTHMIYKLMkPxMug3HgCac2bcGhtUytRHVLsR6xJ0f6UwLo2kTbqjuRkd1HP8YLQGp4jVzVnzreIXn8/HkPtn9+UI/ZEJKhBDCRyZHEdNiUNTRb3KR0ECg3yxn4I8+4QjcXpyusBDuxOWHKYrGRl61Vcv0tUViirUQJoLS7AN9pnTp/Gdg5U/ax8XOgxK+i7o+xflw8a1TnWzw4MZO232fHrai2XqWg7dV8pzqvjnHdnv80mBmE2dmSE9/HRYOYZpen8MVU9tnr7BGTfs5IVzhnWJydGqwyvNdEiwfLG/BAboTrZXWDKgoZbDsLuue5Q7h094khOo/0B2W9rMSvYu4GVbrRWBGyD6oB7xwGyiCFtnWaIE4liHGwHd21hMrdrtdpoBf/xkSic/yUjwrpNuqFXS7UOMoQlwY+WXtYWjohG5O2Xqaa4+jmclX61w94SzY94XGI6gjmDuMiGBmsTJ3ih80MSVDZsG5Jr5JYGh5IErrOI7leW2bGzC2Zb6071DEWOwU/5QexYvwRL0HqB21So0RTeFCHDrjz1tZOUffoHGOFYgH8O0M3rbIqpuCBBoEgdjw+XsYLp+y842ZWxtwkjKY0BsPut9OvoUsENt8LD4YrAQ4AeCX3M4oq3UHXSTcZptffCWgOEB9dZHL+eG9O7N8WRDgL9lArEZEokcxOE=

